name: ci testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  synthetic_rabbitmq:
    name: "Synthetic Tests with RabbitMQ"
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: bitnami/rabbitmq:3.8
        env:
          RABBITMQ_USERNAME: admin
          RABBITMQ_PASSWORD: admin
          RABBITMQ_VHOST: test
        ports:
        - 5672:5672
        - 15672:15672
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install HTCondor
      run: |
        curl -fsSL https://get.htcondor.org | sudo /bin/bash -s -- --no-dry-run
        sudo cat >/etc/condor/config.d/99_custom.conf <<EOF
        BIND_ALL_INTERFACES = True
        TOOL_DEBUG = D_FULLDEBUG
        EOF
        condor_q -version
    - name: Install dependencies
      id: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wipac-mqclient[rabbitmq] htcondor
    - name: Test
      run: |
        cd synthetic/rabbitmq
        python submit.py --address amqp://admin:admin@localhost/test/channel --scratch $PWD/scratch --loglevel debug
