name: ci testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  synthetic_rabbitmq:
    name: "Synthetic Tests with RabbitMQ"
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: bitnami/rabbitmq:3.8
        env:
          RABBITMQ_USERNAME: admin
          RABBITMQ_PASSWORD: admin
          RABBITMQ_VHOST: test
        ports:
        - 5672:5672
        - 15672:15672
    env:
      _CONDOR_SEC_CLAIMTOBE_USER: "submituser"
      _CONDOR_SEC_DEFAULT_AUTHENTICATION_METHODS: "CLAIMTOBE"
      _CONDOR_TOOL_DEBUG: "D_FULLDEBUG"
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install HTCondor
      run: |
        sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y curl
        curl -fsSL https://get.htcondor.org | sudo /bin/bash -s -- --no-dry-run
        sleep 10
        condor_status
        condor_q
    - name: Install dependencies
      id: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wipac-mqclient[rabbitmq] htcondor
    - name: Test
      run: |
        cd synthetic/rabbitmq
        python submit.py --address amqp://admin:admin@localhost/test/channel --scratch $PWD/scratch --loglevel debug
