name: ci testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  synthetic_rabbitmq:
    name: "Synthetic Tests with RabbitMQ"
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: bitnami/rabbitmq:3.8
        env:
          RABBITMQ_USERNAME: admin
          RABBITMQ_PASSWORD: admin
          RABBITMQ_VHOST: test
        ports:
        - 5672:5672
        - 15672:15672
    env:
      PYTHONUNBUFFERED: "1"
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install HTCondor
      run: |
        curl -fsSL https://get.htcondor.org | sudo /bin/bash -s -- --no-dry-run
        sudo tee /etc/condor/config.d/99_custom.conf >/dev/null <<EOF
        BIND_ALL_INTERFACES = True
        TOOL_DEBUG = D_FULLDEBUG
        EOF
        condor_q -version
    - name: Install dependencies
      id: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wipac-mqclient[rabbitmq] htcondor
    - name: Test manually
      run: |
        set -e
        cd synthetic/rabbitmq
        python pub.py --address amqp://admin:admin@localhost/test/manual --num-msgs 10 --batch-size 10 &
        pid=$!
        python worker.py --address amqp://admin:admin@localhost/test/manual --num-msgs 10 --batch-size 10 --delay 0
        if ps | grep "$pid[^[]" >/dev/null
        then
          echo "pub.py still running"
          exit 1
        else
          wait $pid
          exit $?
        fi
    - name: Test with HTCondor
      run: |
        cd synthetic/rabbitmq
        python submit.py --address amqp://admin:admin@localhost/test/channel --scratch $PWD/scratch --loglevel debug
